baseURL = 'https://tldrtravel.info/'
languageCode = 'en-us'
title = 'tl;dr: Travel Info'
theme = 'hugo-book'


# Hugo Book theme configuration
# https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/config.toml
enableGitInfo = true

[params]
  BookTheme = 'auto'
  BookSection = '/'
  BookRepo = 'https://github.com/TheStalwart/travel-notes'
